// DeskRPG 오피스 룩 50종 — dandacompany/deskrpg src/game/three/office-looks*.ts 에서 추출.
// DeskRPG 가 룩을 바꾸면 validateOfficeAppearance 가 'unknown office look' 으로 거절한다 → 다시 추출.
export const OFFICE_LOOKS = [
  { id: "office-jun", bodyType: "male" },
  { id: "office-tae", bodyType: "male" },
  { id: "office-seo", bodyType: "female" },
  { id: "office-min", bodyType: "male" },
  { id: "office-do", bodyType: "male" },
  { id: "office-yun", bodyType: "female" },
  { id: "office-ha", bodyType: "female" },
  { id: "office-jin", bodyType: "male" },
  { id: "office-eun", bodyType: "female" },
  { id: "office-hyeon", bodyType: "male" },
  { id: "office-nari", bodyType: "female" },
  { id: "office-roan", bodyType: "male" },
  { id: "office-soi", bodyType: "female" },
  { id: "office-yul", bodyType: "male" },
  { id: "office-bomi", bodyType: "female" },
  { id: "office-jiho", bodyType: "male" },
  { id: "office-dami", bodyType: "female" },
  { id: "office-seul", bodyType: "female" },
  { id: "office-kyu", bodyType: "male" },
  { id: "office-ara", bodyType: "female" },
  { id: "office-ian", bodyType: "male" },
  { id: "office-rumi", bodyType: "female" },
  { id: "office-gonu", bodyType: "male" },
  { id: "office-haena", bodyType: "female" },
  { id: "office-woojin", bodyType: "male" },
  { id: "office-jua", bodyType: "female" },
  { id: "office-taemin", bodyType: "male" },
  { id: "office-sera", bodyType: "female" },
  { id: "office-hosu", bodyType: "male" },
  { id: "office-yena", bodyType: "female" },
  { id: "office-sungho", bodyType: "male" },
  { id: "office-hyejin", bodyType: "female" },
  { id: "office-jungwon", bodyType: "female" },
  { id: "office-seok", bodyType: "male" },
  { id: "office-mira", bodyType: "female" },
  { id: "office-kyung", bodyType: "male" },
  { id: "office-yeon", bodyType: "female" },
  { id: "office-dohun", bodyType: "male" },
  { id: "office-suhye", bodyType: "female" },
  { id: "office-jaewon", bodyType: "male" },
  { id: "office-daeun", bodyType: "female" },
  { id: "office-jiseok", bodyType: "male" },
  { id: "office-seona", bodyType: "female" },
  { id: "office-haram", bodyType: "female" },
  { id: "office-chan", bodyType: "male" },
  { id: "office-eunsol", bodyType: "female" },
  { id: "office-sejin", bodyType: "male" },
  { id: "office-hyo", bodyType: "female" },
  { id: "office-yumin", bodyType: "male" },
  { id: "office-garam", bodyType: "female" },
];

export const OFFICE_LOOK_IDS = OFFICE_LOOKS.map((l) => l.id);
